### PR TITLE
Update generate_from_simbev to work with SimBEV v1.0.0

### LINKED ISSUE #11: Adapt spiceEV to use simBEV's new output format and metadata to parametrize generate_from_simbev.py
As soon as there's a meta dataset (https://github.com/rl-institut/simbev/issues/27) for a run

- [ ] Use the vehicle data to parametrize `generate_from_simbev.py`: `vehicle_types` [here](https://github.com/rl-institut/spice_ev/blob/ffb9662a3fc95018b543d7b118e33f3ab3e1d324/generate_from_simbev.py#L65-L108) including `battery_efficiency` for each vehicle (side note: default set in ffb9662a3fc95018b543d7b118e33f3ab3e1d324)
- [ ] Other values as listed in https://github.com/rl-institut/simbev/issues/27

### PR DESCRIPTION
**Pull request by mosc5**
Fix #11

**Changes proposed in this pull request**:
- Update generate from simbev to use metadata and new output format
- Add new command line option to choose one region to generate from

The following steps were realized, as well (required):
- [x] Correct linting with `flake8 path_to_script`
- [x] Check if tests pass locally (`pytest ./src/tests.py`)

Also the following steps were realized (if applies):
- [x] Write docstrings to your code
- [ ] For new functionalities: Explain in readthedocs
- [ ] Write test(s) for your new patch of code

### CODE REVIEW

**Comment by mosc5** [comment]
Getting the following error when using the option `--save-timeseries`:

`  File "C:\Users\mosc\PycharmProjects\spice_ev\src\scenario.py", line 282, in run
    report.save_gc_timeseries(self, gcID, output_path)
  File "C:\Users\mosc\PycharmProjects\spice_ev\src\report.py", line 407, in save_gc_timeseries
    if gcID not in scenario.flex_bands.keys():
AttributeError: 'Scenario' object has no attribute 'flex_bands'`

**Review by stefansc1 — APPROVED** [review]

**Comment by jakobgemassmer** [comment]
The output grafic from SpiceEV could be adjusted, @stefansc1. I think it would help the user, if all subplots would have the same x-axis (ticks).
grafik

**Comment by jakobgemassmer** [comment]
The charging behaviour seems to be correct. However, I found one issue:
In the example files (region1), the medium-BEV has a start_soc of 0.449, which is read correct:
grafik
At the first charging station it charges with 150 kW, over 15 minutes to charge to soc=0.8. This charging power is saved in the timeseries output. But the simulation says the soc before the charging event is 0.786533333333333 and soc_delta=-0.0583.
grafik

In my understanding this doesn't add up. What is the reason for these values? @stefansc1 @mosc5

**Comment by stefansc1** [comment]
I addressed the time axis issue in commit fd222c97
Maybe the second issue (deviation of SoC from expected value) is caused by when the SoC is updated. In the SimBEV-files, the SoC is given when plugging in, but in SpiceEV, the vehicle SoC (in the output) is given after the first charging interval. Charging from 0.4 to 0.8 in 15 minutes with 150 kW sounds plausible.

**Pull request merged**
